before_script:
  - apt update
stages:
  - test
  
tcpecho_test:
  image: ubuntu:18.04
  stage: test
  script:
  # Installing mono
    - ./install_mono_from_microsoft_deb_packages.sh
    - apt install -y nunit-console
    - time (make && make check)
